### ISSUE TITLE
Does it work in oneplus5？

### ISSUE THREAD

**Issue by huanmingcn** [snowwolf725/Local_Manifest_OnePlus5#1]

**Comment by snowwolf725** [comment]
Yes, it works.
However I recommend you use Local_Manifest from Koenkk.

Ref:
[https://github.com/Koenkk/local_manifest_cheeseburger](https://github.com/Koenkk/local_manifest_cheeseburger)

How to compile LineageOS for OnePlus 5
[http://blog.snowwolf725.jjvk.com/2017/01/08/530/](http://blog.snowwolf725.jjvk.com/2017/01/08/530/)

**Comment by huanmingcn** [comment]
Thank you very much.
